'use strict';

import * as Utils from '../utils/constants';

export default Utils.addPrefix([
  'SMSCODE_REQUEST_START',
  'SMSCODE_REQUEST_SUCCESS',
  'SMSCODE_REQUEST_FAILURE',

  'SMSCODE_COUNTDOWN_START',
  'SMSCODE_COUNTDOWN',
  'SMSCODE_COUNTDOWN_END',

  'PHONE_LOGIN_REQUEST_START',
  'PHONE_LOGIN_REQUEST_SUCCESS',
  'PHONE_LOGIN_REQUEST_FAILURE',

  'PHONE_LOGIN_CLEANUP',
  'PHONE_LOGIN_FORMFIELD_CHANGE'
], 'MAXLOGIN_');
